export const ContestQuery = {
    CONTEST_LIST: 'CONTEST_LIST',
    WINNER_LIST:'WINNER_LIST',
    BOOK_LIST: 'BOOK_LIST',
    PARTICIPATION_RULE:'PARTICIPATION_RULE',
    'LEADERBOARD_LIST':'LEADERBOARD_LIST'
  }
  