export const UserProfileQuery = {
  LIBRARY_LIST: 'LIBRARY_LIST',
  BOUGHT_PRODUCT_LIST: 'BOUGHT_PRODUCT_LIST',
  TRANSACTION_HISTORY_LIST: 'TRANSACTION_HISTORY_LIST',
  ORIGINAL_WORK_LIST: 'ORIGINAL_WORK_LIST',
  AUTHOR_DATA: 'AUTHOR_DATA',
  AUTHOR_WORKS: 'AUTHOR_WORKS',
}
