export const ContestQuery = {
    PARTICIPATION_RULE: 'PARTICIPATION_RULE',
    'SUBMISSION_TIMELINE': 'SUBMISSION_TIMELINE',
    'JUDGING_TIMELINE': 'JUDGING_TIMELINE',
    'JUDGEMENT_RULE': 'JUDGEMENT_RULE',
    'BOOK_DETAILS':'BOOK_DETAILS',
    'THEME_LIST':'THEME_LIST',
    'PRIZE_LIST':'PRIZE_LIST',
    'ONGOING_EVENTS':'ONGOING_EVENTS'
}