export const PaymentQuery = {
  SUBSCRIPTION_LIST: 'SUBSCRIPTION_LIST',
  VOTE_PLAN_LIST: 'VOTE_PLAN_LIST',
  COIN_PLAN_LIST: 'COIN_PLAN_LIST',
  CURRENT_SUBSCRIPTION: 'CURRENT_SUBSCRIPTION',
  PAYMENT_STATUS: 'PAYMENT_STATUS',
  // SUBSCRIPTION_LIST: 'SUBSCRIPTION_LIST',
}
