export const PaymentQuery = {
  SUBSCRIPTION_LIST: 'SUBSCRIPTION_LIST',
  VOTE_PLAN_LIST: 'VOTE_PLAN_LIST',
  CURRENT_SUBSCRIPTION: 'CURRENT_SUBSCRIPTION',
  // SUBSCRIPTION_LIST: 'SUBSCRIPTION_LIST',
}
